carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('vaciar', views.clear, name='clear')
]

cyberShop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('acerca/', views.about, name='about'),
    path('', ProductListView.as_view(), name='index'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order')
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
    path('nuevo/', views.new, name='new'),
    path('<slug:slug>/editar', views.edit, name='edit'),
    path('<slug:slug>/borrar', views.delete, name='delete'),
]

carts/models.py
from django.db import models
from users.models import User
from products.models import Product
from django.db.models.signals import pre_save, m2m_changed, post_save
import uuid
import decimal

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=16, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=16, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.0 #Impuestos

    def __str__(self):
        return self.cart_id
    
    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total()

    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
        ])
        self.save()
    
    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')
    
    @property
    def order(self):
        return self.order_set.first()

class CartProductsManager(models.Manager):
    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)
        if not created:
            quantity = object.quantity + quantity

        object.update_quantity(quantity)
        return object

class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args,**kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

carts/views.py
import products
from django.shortcuts import get_object_or_404, render, redirect
from .utils import get_or_create_cart
from products.models import Product
from .models import CartProducts
# Create your views here.

def cart(request):   
    cart = get_or_create_cart(request)
    return render(request, 'carts/cart.html',{
        'cart': cart
    })

def add(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    if int(request.POST.get('quantity', 1)) < 1:
        quantity = 1
    else:
        quantity = int(request.POST.get('quantity', 1))
    
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart,
                                                                    product=product, 
                                                                    quantity=quantity)
    return render(request, 'carts/add.html',{
        'quantity':quantity,
        'product': product,
        'cart_product': cart_product
    })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    cart.products.remove(product)
    return redirect('carts:cart')

def clear(request):
    cart = get_or_create_cart(request)
    cart.products.clear()
    return redirect('carts:cart')

carts/templates/carts/add.html
{% extends 'base.html' %}
{% load product_extras %}
{% load cart_extras %}
{% block content %}
    <div class="col">
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="Imagen del producto" width="200" height="200">
        {% endif %}  
    </div>
    <div class="col">
        <h1>{{ product.title }}</h1>
        <h3 class="text-success">
            {{ quantity | quantity_add_format }}
        </h3>
        <h4 class="text-danger">
            {{ product.price | price_format }}
        </h4>
        <a class="btn btn-primary mb-1" href="{% url 'index' %}">
            Volver al inicio
        </a>
        <a class="btn btn-info" href="{% url 'carts:cart' %}">
            Ver carrito
        </a>
    </div>
{% endblock %}

carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load product_extras %}
{% block content %}
    <h1>Carrito</h1>

    {% if cart.products.exists %}

        <div class="col-8 card card-body mb-2">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">Producto</th>
                        <th scope="col" class="text-center">Cantidad</th>
                        <th scope="col" class="text-center">Precio</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.products_related %}
                        {% with product=cp.product %}
                            <tr>
                                <th>
                                    {% if product.image %}
                                        <img src="{{ product.image.url }}" alt="Imagen del producto" width="60" height="60">
                                    {% endif %}
                                    <a class="" href="{% url 'products:product' product.slug %}">
                                        {{ product.title }}
                                    </a>
                                </th>
                                <th class="text-center">{{ cp.quantity }}</th>
                                <th class="text-center">
                                    <span class="text-danger">{{ product.price | price_format }}</span>
                                </th>
                                <th class="text-center">
                                    {% include 'carts/snippets/remove.html' %}
                                </th>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="">
                        Subtotal: <span class="text-danger">{{ cart.subtotal | price_format }}</span>
                    </div>
                    <div class="mt-2">
                        {% include 'carts/snippets/clear.html' %}
                        <a class="btn btn-warning mb-2" href="{% url 'orders:order' %}">Finalizar compra</a>
                    </div>
                </div>
            </div>

        </div>
    {% else %}
        <div class="col">
            <h3>Tu carrito está vacio</h3>
            <a class="btn btn-primary" href="{% url 'index' %}">
                Volver
            </a>
        </div> 
    {% endif %}

{% endblock %}
    