carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
    path('vaciar', views.clear, name='clear')
]

cyberShop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('acerca/', views.about, name='about'),
    path('', ProductListView.as_view(), name='index'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'),
    path('nuevo/', views.new, name='new'),
    path('<slug:slug>/editar', views.edit, name='edit'),
    path('<slug:slug>/borrar', views.delete, name='delete'),
]

templates/about.html
{% extends 'base.html' %}
{% block content %}
<div>
    <img src="/static/images/sobreNosotros.png" alt="Sobre Nosotros" style= "border-radius: 10px; width: 90%;">
</div>
<p style="margin: 40px auto; text-shadow: 0px 0px 5px rgb(255, 255, 255), 0px 0px 15px goldenrod;">
    Somos una empresa global de venta al por menor de artículos en línea.

    CyberShop fue creado por un grupo de personas de distintas generaciones que comparten una misma pasión
    por el anime de DBZ.

    Con el tiempo, la tecnología ha cambiado y también la forma en que hacemos negocios y es por eso que decidimos dar
    un paso hacia la globalización. Ofrecemos una amplia gama de artículos de DBZ, no importa en el país que te
    encuentres, nosotros te haremos llegar el pedido hasta tu país e incluso hasta la puerta de tu casa.

    Nuestro objetivo es proporcionar a nuestros clientes productos de alta calidad a precios competitivos directos de
    fábrica.

    Entendemos las necesidades de nuestros clientes, y por lo tanto, ofrecemos diferentes estilos de artículos, junto
    con un servicio profesional dedicado que satisfaga eficientemente las necesidades de todos nuestros clientes en todo
    el mundo. Garantizamos compartir su pasión por DBZ y el compromiso total con la adquisición de artículos a los
    precios más competitivos.

    Nuestro equipo profesional del Centro de Servicio al Cliente estará listo para ayudarle.

    Su satisfacción es y siempre será nuestra máxima prioridad.
</p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CyberShop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex flex-column h-100" style="background-color: rgba(140, 0, 0, 0.900); color: white;">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    <main class="flex-shrink-0">
        <div class="container">
            <div class="row mt-5 mb-5">
                {% include 'messages.html' %}
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
    {% include 'footer.html' %}    
</body>
<script src="https://kit.fontawesome.com/f8d866bab6.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

templates/footer.html
<footer class="bg-darkorange text-center text-white mt-auto p-3" style="width: 100%; background-color: darkorange;">
  <div class="container" style="color: rgb(255, 255, 255); font-weight: bolder; text-shadow: 0px 0px 5px rgb(252, 0, 0), 0px 0px 15px rgb(255, 0, 0);">
    CyberShop © 2021
    <a class="text-white" href=""></a>
  </div>
</footer>

templates/header.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'logout' as logout %}
{% url 'carts:cart' as cart %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg">
  <div class="container-fluid" style="text-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod; width: 500px; font-size: x-large;">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
    <img src= "{% static 'images/shengLong.jpeg' %}" alt="Logo" width="100px" style="border-radius: 10px; margin: 10px; box-shadow: 0px 0px 5px rgb(231, 127, 9), 0px 0px 15px rgb(255, 233, 39);">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-2">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link">
          <span class="fas fa-user"></span>
          {{user.username}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == logout %}active{% endif %}" href="{{ logout }}">
          <span class="fas fa-sign-in-alt"></span>
          Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == login %}active{% endif %}" href="{{ login }}">
          <span class="fas fa-user"></span>
          Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == register %}active{% endif %}" href="{{ register }}">
          <span class="fas fa-user-plus"></span>
          Registro</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == cart %}active{% endif %}" href="{{ cart }}">
          <span class="fas fa-shopping-cart"></span>
          Carrito</a>
        </li>                      
      </ul>
    </div>
  </div>
</nav>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="col">
    <h1 style="text-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod; text-align: center; margin-bottom: 40px;">{{ title }}</h1>
    <div class="d-flex justify-content-center">
    {% include 'products/snippets/cards.html' %}
    </div>
    {% include 'products/snippets/list.html' %}
</div>
{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
        <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
        {{ message }}
    </div>
{% endfor %}
{% endif %}

templates/navbar.html
{% url 'index' as index %}
{% url 'about' as about %}
{% url 'products:new' as new %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="box-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod;">
  <div class="container-fluid" style="box-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod; background-color: darkorange;">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == index %}active{% endif %}" href="{{ index }}" style="text-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod;">Home</a>
        </li>
        <li class="nav-item dropdown" style="text-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod;">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categorías
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: rgb(207, 169, 0);">
            <li><a class="dropdown-item" href="{% url 'products:search' %}?q=Goku"><img src="/static/images/goku.jpg" alt="" style="width: 40px; height: 40px; border-radius: 10px; border: 1px solid black;"> Goku</a></li>
            <li><a class="dropdown-item" href="{% url 'products:search' %}?q=Buu"><img src="/static/images/boo.jpg" alt="" style="width: 40px; height: 40px; border-radius: 10px; border: 1px solid black;"> Buu</a></li>
            <li><a class="dropdown-item" href="{% url 'products:search' %}?q=Gohan"><img src="/static/images/gohan.jpg" alt="" style="width: 40px; height: 40px; border-radius: 10px; border: 1px solid black;"> Gohan</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == about %}active{% endif %}" href="{{ about }}" style="text-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod;">Conocenos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="mailto:cybershop@correo.com" style="text-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod;">Contacto</a>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == new %}active{% endif %}" href="{{ new }}">Nuevo Producto</a>
        </li>
        {% endif %}                        
      </ul>
      <form class="d-flex" action="{% url 'products:search' %}">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" name="q" value="{{ query }}">
        <button class="btn btn-outline-success" type="submit" style="text-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod; box-shadow: 0px 0px 5px gold, 0px 0px 15px goldenrod;color: white; border: black;">Buscar</button>
      </form>
    </div>
  </div>
</nav>